name: Generate and Deploy Documentation Website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build HTML from AsciiDoc
        run: |
          cd asciidoc-samples
          docker run --rm -v ${{ github.workspace }}/asciidoc-samples:/documents asciidoctor/docker-asciidoctor:latest asciidoctor --destination-dir=../docs sensitive-data-sop.adoc
